config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: :about

  devise_for :users

  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :create, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true #optionalをtrueにしないと保存されない？
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email] )
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @new_book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(current_user.id)
    @new_book = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def create
    @user = User.find(current_user.id)
    @books = Book.all
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:create] = "You have created book successfully."
      redirect_to book_path(@new_book.id)
    else
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:book_update] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @users = User.all
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:user_update] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/errorbook', new_book: @book %>

      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title , class:"form-control" %>
      </div>
      <div class="form-group">
        <label for="inputOpinion">Opinion</label>
        <%= f.text_area :body , class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book" , class:"btn btn-success"%>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errorbook', new_book: @new_book %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/userinfo', user: @user %>
      <%= render 'layouts/newbook', new_book: @new_book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= link_to image_tag(book.user.get_image(100,100)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fas fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="far fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>コメント数: <%= book.book_comments.count %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/userinfo', user: @book.user %>
      <%= render 'layouts/newbook', new_book: @new_book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= link_to image_tag(@book.user.get_image(100,100)), user_path(@book.user.id) %>
              <br><%= link_to @book.user.name, user_path(@book.user.id) %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fas fa-heart"></i><%= @book.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="far fa-heart"></i><%= @book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>コメント数: <%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book.id) , class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" , class: "btn btn-sm btn-danger" %></td>
          <% end %>
          </tr>
        </tbody>
      </table>
      <div>
        <table>
          <tbody>
            <% @book.book_comments.each do |book_comment| %>
              <tr>
                <td>
                  <%= link_to image_tag(book_comment.user.get_image(100,100)), user_path(book_comment.user.id) %>
                  <br><%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
                </td>
                <td>
                  <%= book_comment.comment %>
                </td>
                <td>
                  <% if book_comment.user == current_user %>
                    <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete , class: "btn btn-sm btn-danger" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
        <div class="form-group">
          <%= f.text_area :comment , class:"form-control" , rows:"5" %>
        </div>
        <div class="form-group">
          <%= f.submit "送信"  %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h1>Welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-7">
      <h1>welcome to <i class="fa fa-book" aria-hidden="true"></i><strong>Bookers&nbsp;!!</strong></h1>
      <p>In <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="row">
        <div class="mx-auto col-10">
          <a class="btn btn-info btn-sm btn-block" href="/users/sign_in">Log in</a>
          <a class="btn btn-success btn-sm btn-block" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>　

app/views/layouts/_errorbook.html.erb
<% if new_book.errors.any? %>
  <% if new_book.errors.count==1 %>
    <%= new_book.errors.count %>&nbsp;error prohibited this obj from being saved:
  <% else %>
    <%= new_book.errors.count %>&nbsp;errors prohibited this obj from being saved:
  <% end %>
  <ul>
    <% new_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_erroruser.html.erb
<% if user.errors.any? %>
  <% if user.errors.count==1 %>
    <%= user.errors.count %>&nbsp;error prohibited this user from being saved:
  <% else %>
    <%= user.errors.count %>&nbsp;errors prohibited this user from being saved:
  <% end %>
  <ul>
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_newbook.html.erb
<h2 class="mt-5">New book</h2>
<%= form_with model: new_book do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class:"form-control", id:"book_title" %>
  </div>
  <div class="form-group">
    <label for="book_body">Opinion</label>
    <%= f.text_area :body, class:"form-control", id:"book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success"  %>
  </div>
<% end %>

app/views/layouts/_notification.html.erb
    <div class="Notification">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: key %>
      <% end %>
    </div>

app/views/layouts/_userinfo.html.erb
<h2>User info</h2>
  <%= image_tag user.get_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr></tr>
    </tbody>
  </table>
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog" aria-hidden="true"></i>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
            <div class="collapse navbar-collapse">
              <ul class="ml-auto navbar-nav">
                <% if user_signed_in? %>
                  <li class="nav-link">
                    <%= link_to user_path(current_user.id) , class:"text-light" do %>
                    <i class="fas fa-home" aria-hidden="true"></i>
                    <span>Home</span>
                    <% end %>
                  </li>
                  <li class="nav-link">
                    <%= link_to users_path , class:"text-light" do %>
                    <i class="fas fa-users" aria-hidden="true"></i>
                    <span>Users</span>
                    <% end %>
                  </li>
                  <li class="nav-link">
                    <%= link_to books_path, class:"text-light" do %>
                    <i class="fas fa-book-open" aria-hidden="true"></i>
                    <span>Books</span>
                    <% end %>
                  </li>
                  <li class="nav-link">
                    <%= link_to destroy_user_session_path, method: :delete , class:"text-light" do %>
                    <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                    <span>logout</span>
                    <% end %>
                  </li>
                <% else %>
                  <li class="nav-link">
                    <%= link_to root_path , class:"text-light" do %>
                    <i class="fas fa-home" aria-hidden="true"></i>
                    <span>Home</span>
                    <% end %>
                  </li>
                  <li class="nav-link">
                    <%= link_to about_path , class:"text-light" do %>
                    <i class="fas fa-link" aria-hidden="true"></i>
                    <span>About</span>
                    <% end %>
                  </li>
                  <li class="nav-link">
                    <%= link_to new_user_registration_path , class:"text-light" do %>
                    <i class="fas fa-user-plus" aria-hidden="true"></i>
                    <span>sign up</span>
                    <% end %>
                  </li>
                  <li class="nav-link">
                    <%= link_to new_user_session_path , class:"text-light" do %>
                    <i class="fas fa-sign-in-alt" aria-hidden="true"></i>
                    <span>login</span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/notification' %>
    <%= yield %>
  </body>
  <footer>
    <div class="container">
      <div class="row">
        <div class="mx-auto mt-5 mb-5">
          CopyRight Infratop.inc
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'layouts/erroruser', user: @user %>
      
      <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name , class:"form-control" %>
      </div>
      <div class="form-group">
        <label for="inputImage">Image</label>
        <by><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" , class:"form-control-file" %>
      </div>
      <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
        <%= f.text_area :introduction , class:"form-control"%>
      </div class="form-group">
        <%= f.submit "Update User" , class:"btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/userinfo', user: @user %>

      <%= render 'layouts/newbook', new_book: @new_book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= link_to image_tag(user.get_image(100,100)), user_path(user.id) %></td>
              <td><%= user.name %></td>
              <td></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/userinfo', user: @user %>
      <%= render 'layouts/newbook', new_book: @new_book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= link_to image_tag(book.user.get_image(100,100)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fas fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="far fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>コメント数: <%= book.book_comments.count %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>